# Exercício Python 012: Faça um algoritmo que leia o preço de um produto
#e mostre seu novo preço, com 5% de desconto.
import random
import time

tempo = time.strftime('%H:%M', time.localtime())

print('\033[31m-=\033[m' * 55)
print(' ' * 13, 'Bem Vindo(a) a o mercado do desconto aleatorio, isso mesmo desconto aleatorio!!!!')
print(' ')
print(' ' * 10, '\033[2;32;41|promoções por horario:\033[m')
print(' ' * 11, '\033[2;34m|de manha a promoção vai de 0% até 80%')
print(' ' * 11, '|de tarde a promoção vai de 0% até 40%')
print(' ' * 11, '|de madruga a promoção vai de 0% até 30%\033[m')
print('\033[31m-=\033[m' * 55)
time.sleep(5)


print('veja os nossos produtos: ')
print('\033[2;32m-\033[m' * 30)
time.sleep(1.5)
print('\033[36m1-arroz R$9.60')
time.sleep(1.5)
print('2-feijão R$7.99')
time.sleep(1.5)
print('3-leite R$5.20')
time.sleep(1.5)
print('4-açúcar R$6.99')
time.sleep(1.5)
print('5-doritos R$23.99')
time.sleep(1.5)
print('6-chocolates')
time.sleep(1.5)
print('7-café R$8.99\033[m')
time.sleep(1.5)
print('\033[2;32m-\033[m' * 30)

escolha = input('escolha entre 1 a 7: ')
print('\033[2;32m-\033[m' * 30)
time.sleep(0.8)

if tempo >= '5:00' and tempo <= '12:00':
    promocao = random.randint(0, 80)
    a = escolha.isnumeric()

    if a == True and escolha < '8':
        print('analisando a sua escolha')
    else:
        print('ERROR 404, escolha apenas entre 1 até 7.')
        print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
        exit()

    if escolha == '1':
        time.sleep(0.8)
        print('você escolheu o arroz')
        time.sleep(1.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 9.60 - (9.60 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você quer comprar? (s/n) ').strip().lower()
        time.sleep(2)
        if yes_or_no == 's':
            print('você comprou. tenha um bom usufruimento com a sua nova compra!!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '2':
        time.sleep(0.8)
        print('você escolheu o feijão!')
        time.sleep(1.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 7.99 - (7.99 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar? (s/n) ').strip().lower()
        time.sleep(2)
        if yes_or_no == 's':
            print('você comprou. tenha um bom usufruimento com a sua nova compra!!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '3':
        time.sleep(0.8)
        print('você escolheu o leite')
        time.sleep(1.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 5.20 - (5.20 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar? (s/n) ').strip().lower()
        time.sleep(2.0)
        if yes_or_no == 's':
            print('você comprou. tenha um bom usufruimento com a sua nova compra!!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '4':
        time.sleep(0.8)
        print('você escolheu o açucar.')
        time.sleep(0.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 6.99 - (6.99 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar? (s/n) ').strip().lower()
        time.sleep(2)
        if yes_or_no == 's':
            print('você comprou. tenha um bom usufruimento com a sua nova compra!!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '5':
        time.sleep(0.8)
        print('você escolheu o doritos.')
        time.sleep(0.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 23.99 - (23.99 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar?  (s/n) ').strip().lower()
        if yes_or_no == 's':
            print('você comprou. você teve a melhor escolha possivel!!! proveite bem.')
            print('volte sempre!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '6':
        time.sleep(0.8)
        print('você escolheu a sessão "chocolates"')
        time.sleep(0.8)
        print('temos 3 variedades aki:')
        time.sleep(0.8)
        print('1-lindt R$24.50')
        time.sleep(1)
        print('2-danke R$14.99')
        time.sleep(1)
        print('3-milka R$14.79')
        time.sleep(0.8)
        escolha2 = input('escolha entre 1 a 3: ')
        b = escolha2.isnumeric()
        if b == True and escolha2 < '4':
            time.sleep(0.8)
            print('analisando a sua escolha')
            time.sleep(0.8)
            if escolha2 == '1':
                print('você escolheu lindt')
                time.sleep(0.8)
                print(f'a promoção vai ser {promocao}%')
                time.sleep(0.8)
                soma = 24.50 - (24.50 * promocao / 100)
                yes_or_no = input(f'o preço vai ser R${soma:.2f}. vai querer comprar? (s/n) ').strip().lower()
                if yes_or_no == 's':
                    print('RICO? ME COME!')
                    time.sleep(0.8)
                    print('sua compra foi feita!')
                    time.sleep(0.8)
                    print('volte sempre!')
                elif yes_or_no == 'n':
                    print('tudo bem, venha outro dia.')
                    exit()
                else:
                    print('ERROR 404, escolha apenas s ou n.')
                    time.sleep(0.8)
                    print('TU É BURRO É ??????????????????? S OU CLARO??????')
                    time.sleep(0.8)
                    print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
                    time.sleep(0.8)
                    exit()
            elif escolha2 == '2':
                time.sleep(0.8)
                print('você escolheu danke!')
                time.sleep(0.8)
                print(f'a promoção vai ser {promocao}')
                time.sleep(0.8)
                soma = 14.99 - (14.99 * promocao / 100)
                yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar? (s/n').strip().lower()
                time.sleep(0.8)
                if yes_or_no == 's':
                    print('esse é bom em.')
                    time.sleep(0.8)
                    print('sua compra foi feita!')
                    time.sleep(0.8)
                    print('volte sempre!!!')
                elif yes_or_no == 'n':
                    print('tudo bem, venha outro dia.')
                    exit()
                else:
                    print('ERROR 404, escolha apenas s ou n.')
                    time.sleep(0.8)
                    print('TU É BURRO É ??????????????????? S OU CLARO??????')
                    time.sleep(0.8)
                    print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
                    time.sleep(0.8)
                    exit()
            elif escolha2 == '3':
                time.sleep(0.8)
                print('você escolheu o milka')
                time.sleep(0.8)
                print(f'a promoção vai ser {promocao}')
                time.sleep(0.8)
                soma = 14.79 - (14.79 * promocao / 100)
                yes_or_no = input(f'o preço vai ser R${soma:.2f}. vai querer comprar? (s/n)').strip().lower()
                if yes_or_no == 's':
                    print('esse é bom em, amo comer milka.')
                    time.sleep(0.8)
                    print('sua compra foi feita!')
                    time.sleep(0.8)
                    print('volte sempre!!!')
                elif yes_or_no == 'n':
                    print('tudo bem, volte em outro dia.')
                    exit()
                else:
                    print('ERROR 404, escolha apenas s ou n.')
                    time.sleep(0.8)
                    print('TU É BURRO É ??????????????????? S OU CLARO??????')
                    time.sleep(0.8)
                    print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
                    time.sleep(0.8)
                    exit()
        else:
            print('ERROR 404, escolha apenas entre 1 até 3.')
            time.sleep(0.8)
            print('TU É BURRO É ???????????????????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '7':
        time.sleep(0.8)
        print('você escolheu o café')
        time.sleep(0.8)
        print(f'a promoção vai ser {promocao}')
        time.sleep(0.8)
        soma = 8.99 - (8.99 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. vai querer comprar? (s/n) ').strip().lower()
        if yes_or_no == 's':
            print('café, como sempre, mt bom.')
            time.sleep(0.8)
            print('sua compra foi feita!')
            time.sleep(0.8)
            print('volte sempre!!!')
        elif yes_or_no == 'n':
            print('tudo bem, volte em outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()

elif tempo > '12:00' and tempo <= '17:59':
    promocao = random.randint(0, 40)
    a = escolha.isnumeric()

    if a == True and escolha < '8':
        print('analisando a sua escolha')
    else:
        print('ERROR 404, escolha apenas entre 1 até 7.')
        print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
        exit()

    if escolha == '1':
        time.sleep(0.8)
        print('você escolheu o arroz')
        time.sleep(1.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 9.60 - (9.60 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você quer comprar? (s/n) ').strip().lower()
        time.sleep(2)
        if yes_or_no == 's':
            print('você comprou. tenha um bom usufruimento com a sua nova compra!!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '2':
        time.sleep(0.8)
        print('você escolheu o feijão!')
        time.sleep(1.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 7.99 - (7.99 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar? (s/n) ').strip().lower()
        time.sleep(2)
        if yes_or_no == 's':
            print('você comprou. tenha um bom usufruimento com a sua nova compra!!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '3':
        time.sleep(0.8)
        print('você escolheu o leite')
        time.sleep(1.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 5.20 - (5.20 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar? (s/n) ').strip().lower()
        time.sleep(2.0)
        if yes_or_no == 's':
            print('você comprou. tenha um bom usufruimento com a sua nova compra!!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '4':
        time.sleep(0.8)
        print('você escolheu o açucar.')
        time.sleep(0.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 6.99 - (6.99 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar? (s/n) ').strip().lower()
        time.sleep(2)
        if yes_or_no == 's':
            print('você comprou. tenha um bom usufruimento com a sua nova compra!!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '5':
        time.sleep(0.8)
        print('você escolheu o doritos.')
        time.sleep(0.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 23.99 - (23.99 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar?  (s/n) ').strip().lower()
        if yes_or_no == 's':
            print('você comprou. você teve a melhor escolha possivel!!! proveite bem.')
            print('volte sempre!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '6':
        time.sleep(0.8)
        print('você escolheu a sessão "chocolates"')
        time.sleep(0.8)
        print('temos 3 variedades aki:')
        time.sleep(0.8)
        print('1-lindt R$24.50')
        time.sleep(1)
        print('2-danke R$14.99')
        time.sleep(1)
        print('3-milka R$14.79')
        time.sleep(0.8)
        escolha2 = input('escolha entre 1 a 3: ')
        b = escolha2.isnumeric()
        if b == True and escolha2 < '4':
            time.sleep(0.8)
            print('analisando a sua escolha')
            time.sleep(0.8)
            if escolha2 == '1':
                print('você escolheu lindt')
                time.sleep(0.8)
                print(f'a promoção vai ser {promocao}%')
                time.sleep(0.8)
                soma = 24.50 - (24.50 * promocao / 100)
                yes_or_no = input(f'o preço vai ser R${soma:.2f}. vai querer comprar? (s/n) ').strip().lower()
                if yes_or_no == 's':
                    print('RICO? ME COME!')
                    time.sleep(0.8)
                    print('sua compra foi feita!')
                    time.sleep(0.8)
                    print('volte sempre!')
                elif yes_or_no == 'n':
                    print('tudo bem, venha outro dia.')
                    exit()
                else:
                    print('ERROR 404, escolha apenas s ou n.')
                    time.sleep(0.8)
                    print('TU É BURRO É ??????????????????? S OU CLARO??????')
                    time.sleep(0.8)
                    print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
                    time.sleep(0.8)
                    exit()
            elif escolha2 == '2':
                time.sleep(0.8)
                print('você escolheu danke!')
                time.sleep(0.8)
                print(f'a promoção vai ser {promocao}')
                time.sleep(0.8)
                soma = 14.99 - (14.99 * promocao / 100)
                yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar? (s/n').strip().lower()
                time.sleep(0.8)
                if yes_or_no == 's':
                    print('esse é bom em.')
                    time.sleep(0.8)
                    print('sua compra foi feita!')
                    time.sleep(0.8)
                    print('volte sempre!!!')
                elif yes_or_no == 'n':
                    print('tudo bem, venha outro dia.')
                    exit()
                else:
                    print('ERROR 404, escolha apenas s ou n.')
                    time.sleep(0.8)
                    print('TU É BURRO É ??????????????????? S OU CLARO??????')
                    time.sleep(0.8)
                    print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
                    time.sleep(0.8)
                    exit()
            elif escolha2 == '3':
                time.sleep(0.8)
                print('você escolheu o milka')
                time.sleep(0.8)
                print(f'a promoção vai ser {promocao}')
                time.sleep(0.8)
                soma = 14.79 - (14.79 * promocao / 100)
                yes_or_no = input(f'o preço vai ser R${soma:.2f}. vai querer comprar? (s/n)').strip().lower()
                if yes_or_no == 's':
                    print('esse é bom em, amo comer milka.')
                    time.sleep(0.8)
                    print('sua compra foi feita!')
                    time.sleep(0.8)
                    print('volte sempre!!!')
                elif yes_or_no == 'n':
                    print('tudo bem, volte em outro dia.')
                    exit()
                else:
                    print('ERROR 404, escolha apenas s ou n.')
                    time.sleep(0.8)
                    print('TU É BURRO É ??????????????????? S OU CLARO??????')
                    time.sleep(0.8)
                    print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
                    time.sleep(0.8)
                    exit()
        else:
            print('ERROR 404, escolha apenas entre 1 até 3.')
            time.sleep(0.8)
            print('TU É BURRO É ???????????????????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '7':
        time.sleep(0.8)
        print('você escolheu o café')
        time.sleep(0.8)
        print(f'a promoção vai ser {promocao}')
        time.sleep(0.8)
        soma = 8.99 - (8.99 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. vai querer comprar? (s/n) ').strip().lower()
        if yes_or_no == 's':
            print('café, como sempre, mt bom.')
            time.sleep(0.8)
            print('sua compra foi feita!')
            time.sleep(0.8)
            print('volte sempre!!!')
        elif yes_or_no == 'n':
            print('tudo bem, volte em outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
else:
    promocao = random.randint(0, 30)
    a = escolha.isnumeric()

    if a == True and escolha < '8':
        print('analisando a sua escolha')
    else:
        print('ERROR 404, escolha apenas entre 1 até 7.')
        print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
        exit()

    if escolha == '1':
        time.sleep(0.8)
        print('você escolheu o arroz')
        time.sleep(1.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 9.60 - (9.60 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você quer comprar? (s/n) ').strip().lower()
        time.sleep(2)
        if yes_or_no == 's':
            print('você comprou. tenha um bom usufruimento com a sua nova compra!!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '2':
        time.sleep(0.8)
        print('você escolheu o feijão!')
        time.sleep(1.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 7.99 - (7.99 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar? (s/n) ').strip().lower()
        time.sleep(2)
        if yes_or_no == 's':
            print('você comprou. tenha um bom usufruimento com a sua nova compra!!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '3':
        time.sleep(0.8)
        print('você escolheu o leite')
        time.sleep(1.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 5.20 - (5.20 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar? (s/n) ').strip().lower()
        time.sleep(2.0)
        if yes_or_no == 's':
            print('você comprou. tenha um bom usufruimento com a sua nova compra!!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '4':
        time.sleep(0.8)
        print('você escolheu o açucar.')
        time.sleep(0.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 6.99 - (6.99 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar? (s/n) ').strip().lower()
        time.sleep(2)
        if yes_or_no == 's':
            print('você comprou. tenha um bom usufruimento com a sua nova compra!!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '5':
        time.sleep(0.8)
        print('você escolheu o doritos.')
        time.sleep(0.8)
        print(f'a promoção vai ser {promocao}%')
        time.sleep(0.8)
        soma = 23.99 - (23.99 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar?  (s/n) ').strip().lower()
        if yes_or_no == 's':
            print('você comprou. você teve a melhor escolha possivel!!! proveite bem.')
            print('volte sempre!')
        elif yes_or_no == 'n':
            print('tudo bem, venha outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '6':
        time.sleep(0.8)
        print('você escolheu a sessão "chocolates"')
        time.sleep(0.8)
        print('temos 3 variedades aki:')
        time.sleep(0.8)
        print('1-lindt R$24.50')
        time.sleep(1)
        print('2-danke R$14.99')
        time.sleep(1)
        print('3-milka R$14.79')
        time.sleep(0.8)
        escolha2 = input('escolha entre 1 a 3: ')
        b = escolha2.isnumeric()
        if b == True and escolha2 < '4':
            time.sleep(0.8)
            print('analisando a sua escolha')
            time.sleep(0.8)
            if escolha2 == '1':
                print('você escolheu lindt')
                time.sleep(0.8)
                print(f'a promoção vai ser {promocao}%')
                time.sleep(0.8)
                soma = 24.50 - (24.50 * promocao / 100)
                yes_or_no = input(f'o preço vai ser R${soma:.2f}. vai querer comprar? (s/n) ').strip().lower()
                if yes_or_no == 's':
                    print('RICO? ME COME!')
                    time.sleep(0.8)
                    print('sua compra foi feita!')
                    time.sleep(0.8)
                    print('volte sempre!')
                elif yes_or_no == 'n':
                    print('tudo bem, venha outro dia.')
                    exit()
                else:
                    print('ERROR 404, escolha apenas s ou n.')
                    time.sleep(0.8)
                    print('TU É BURRO É ??????????????????? S OU CLARO??????')
                    time.sleep(0.8)
                    print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
                    time.sleep(0.8)
                    exit()
            elif escolha2 == '2':
                time.sleep(0.8)
                print('você escolheu danke!')
                time.sleep(0.8)
                print(f'a promoção vai ser {promocao}')
                time.sleep(0.8)
                soma = 14.99 - (14.99 * promocao / 100)
                yes_or_no = input(f'o preço vai ser R${soma:.2f}. você vai querer comprar? (s/n')
                time.sleep(0.8)
                if yes_or_no == 's':
                    print('esse é bom em.')
                    time.sleep(0.8)
                    print('sua compra foi feita!')
                    time.sleep(0.8)
                    print('volte sempre!!!')
                elif yes_or_no == 'n':
                    print('tudo bem, venha outro dia.')
                    exit()
                else:
                    print('ERROR 404, escolha apenas s ou n.')
                    time.sleep(0.8)
                    print('TU É BURRO É ??????????????????? S OU CLARO??????')
                    time.sleep(0.8)
                    print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
                    time.sleep(0.8)
                    exit()
            elif escolha2 == '3':
                time.sleep(0.8)
                print('você escolheu o milka')
                time.sleep(0.8)
                print(f'a promoção vai ser {promocao}')
                time.sleep(0.8)
                soma = 14.79 - (14.79 * promocao / 100)
                yes_or_no = input(f'o preço vai ser R${soma:.2f}. vai querer comprar? (s/n)').strip().lower()
                if yes_or_no == 's':
                    print('esse é bom em, amo comer milka.')
                    time.sleep(0.8)
                    print('sua compra foi feita!')
                    time.sleep(0.8)
                    print('volte sempre!!!')
                elif yes_or_no == 'n':
                    print('tudo bem, volte em outro dia.')
                    exit()
                else:
                    print('ERROR 404, escolha apenas s ou n.')
                    time.sleep(0.8)
                    print('TU É BURRO É ??????????????????? S OU CLARO??????')
                    time.sleep(0.8)
                    print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
                    time.sleep(0.8)
                    exit()
        else:
            print('ERROR 404, escolha apenas entre 1 até 3.')
            time.sleep(0.8)
            print('TU É BURRO É ???????????????????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
    elif escolha == '7':
        time.sleep(0.8)
        print('você escolheu o café')
        time.sleep(0.8)
        print(f'a promoção vai ser {promocao}')
        time.sleep(0.8)
        soma = 8.99 - (8.99 * promocao / 100)
        yes_or_no = input(f'o preço vai ser R${soma:.2f}. vai querer comprar? (s/n) ').strip().lower()
        if yes_or_no == 's':
            print('café, como sempre, mt bom.')
            time.sleep(0.8)
            print('sua compra foi feita!')
            time.sleep(0.8)
            print('volte sempre!!! e tenha uma boa madruga')
        elif yes_or_no == 'n':
            print('tudo bem, volte em outro dia.')
            exit()
        else:
            print('ERROR 404, escolha apenas s ou n.')
            time.sleep(0.8)
            print('TU É BURRO É ??????????????????? S OU CLARO??????')
            time.sleep(0.8)
            print('TO INDO DE COMES, AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!')
            time.sleep(0.8)
            exit()
